config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  get 'followers/index'

  get 'followers/destroy'

  resources :followers
  resources :boats
  resources :jobs

  root 'followers#index'

end

app/models/boat.rb
class Boat < ActiveRecord::Base
	belongs_to :user
	has_many :jobs
	has_many :followers
	validates :name, uniqueness: true
	validates :location, inclusion: {in: ["NYC", "LA", "Miami"]} #, "Chicago", "Boston", "New Orleans", "Detroit", "Seattle"]

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/follower.rb
class Follower < ActiveRecord::Base
	belongs_to  :user
	belongs_to :boat
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :boat

	# belongs_to :user, through: :boat

	validates :name, uniqueness: :true
	validates :origin, inclusion: {in: ["Paris", "Tokyo", "London"]}
	validates_numericality_of :cost, :greater_than => 1000.00
	validates :cargo, length: { minimum: 50 }
	validates :destination, inclusion: {in: ["Hong Kong", "Moscow", "Berlin"]}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :boats
  has_many :jobs, through: :boats
  has_many :followers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def index
    # session.clear

    @me = current_user.id
    @boat = Boat.where(user_id: @me)
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = Boat.new(boats_params)
    @boat.save
    redirect_to boats_path
  end

  def edit
    @boat = Boat.find(params[:id])
  end

  def update 
    @boat = Boat.find(params[:id])
    @boat.update(boats_params)
    @boat.save
    redirect_to boats_path
  end

  def destroy
    @boat = Boat.find(params[:id])
    @boat.destroy  
    redirect_to boats_path
  end

  def show
    @boat = Boat.find(params[:id])
    @job = Job.new
    @jobs = Job.where(boat_id: params[:id])
   @follow = Follower.where(:user_id => current_user.id, :boat_id => @boat.id).first
    puts @like

  end

  private
  def boats_params
    params.require(:boat).permit(:avatar, :user_id, :name, :containers, :location)
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  before_action :set_follow, only: [:destroy]
  
	def create
    @follow = Follower.new(user_id: current_user.id, boat_id: params[:boat_id])

    respond_to do |format|
      if @follow.save
        format.html { redirect_to :back, notice: 'follow was successfully created.' }
        format.json { render :show, status: :created, location: @follow }
      else
        format.html { render :new }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end 

  def index
    @me = current_user
  	@follow = Follower.where(user_id: @me)
  	@boat = Boat.all
  end

  def destroy
    @follow.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'follow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow
      @follow = Follower.find(params[:id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@user = User.all
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @boat = Boat.all
  end

  def new
  end

  def create
    @job = Job.new(job_params)
    @job.save
    redirect_to boats_path
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update(job_params)
    redirect_to boats_path
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to boats_path
  end

  def show
    @job = Job.find(params[:id])
  end

  private

  def job_params
    params.require(:job).permit(:boat_id, :name, :containers, :cargo, :origin, :cost, :destination)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boats/create.html.erb
<h1>Boats#create</h1>
<p>Find me in app/views/boats/create.html.erb</p>

app/views/boats/destroy.html.erb
<h1>Boats#destroy</h1>
<p>Find me in app/views/boats/destroy.html.erb</p>

app/views/boats/edit.html.erb
<div class="boat-edit">
	<%= form_for @boat do |f| %>
		Name: <%= f.text_field :name %><br>
		Containers <%= f.text_field :containers %><br>
		location: <%= f.text_field :location %><br>
		<% @me = current_user.id %>
		<%= f.hidden_field :user_id, value: @me %>
		<%= f.submit "Save changes" %>
	<%end%>
</div>

app/views/boats/index.html.erb
<div class="boat-create">	
	<%= form_for Boat.new do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.label :containers %>
		<%= f.text_field :containers %>
		<%= f.label :location %>
		<%= f.text_field :location %>
		<% @me = current_user.id %>
		<%= f.hidden_field :user_id, value: @me %>
		<%= f.file_field :avatar %>
		<%= f.submit "Add boat" %>
	<%end%>
</div>

<% @boat.reverse.each do |boat| %>
	<div class="boat-list">
	<%= link_to boat.name,  boat_path(boat) %>
	<br> 
	</div>
<% end %>

app/views/boats/new.html.erb
<h1>Boats#new</h1>
<p>Find me in app/views/boats/new.html.erb</p>

app/views/boats/show.html.erb
	<% @jobs.reverse.each do |job| %>
		<div class="job-list">
			<%= link_to job.name,  job_path(job) %>
			<br> 
	</div>
<% end %>
</div>
<div class="left">	
	<div class="boat-show">
		<%= image_tag @boat.avatar.url(:medium) %>
		<h1> Name: <%= @boat.name %> </h1> 
		<br>
		<h1>Containers: <%= @boat.containers %> </h1> 
		<h1>Location <%= @boat.location %> </h1> 
		<br>
		<%= link_to "go back", boats_path%> 
		<br>
		<br>
		<% if current_user.id == @boat.user_id %>
			<%= link_to "Edit", edit_boat_path%> | <%= link_to "Delete the boat", boat_path(@boat), method: :delete %>
			<br>
		<% end %>
		<% if !@follow %>
		  <%= button_to 'Follow', {controller: "followers", action: "create", boat_id: params[:id]}, data: { confirm: 'are you sure you want to follow this boat' } %>
		<% else %>
		  <%= button_to 'Unfollow', follower_path(@follow), method: :delete %>
	<% end %>
	</div>
</div>
<br>
<div class="job-create">
	<%= form_for Job.new do |f| %>
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>

		<%= f.label :containers, "# of Containers Required" %><br>
		<%= f.text_field :containers %><br>

		<%= f.label :origin %><br>
		<%= f.text_field :origin %><br>

		<%= f.label :cargo %><br>
		<%= f.text_area :cargo %><br>

		<%= f.label :destination %><br>
		<%= f.text_field :destination %><br>

		<%= f.label :cost %><br>
		<%= f.text_field :cost %><br>

	  <%= f.hidden_field :user_id, value: current_user.id %><br>
	  <%= f.hidden_field :boat_id, value: @boat.id %><br>
	  <%= f.submit %><br>
	<% end %>
</div>

app/views/boats/update.html.erb
<h1>Boats#update</h1>
<p>Find me in app/views/boats/update.html.erb</p>

app/views/followers/destroy.html.erb
<h1>Followers#destroy</h1>
<p>Find me in app/views/followers/destroy.html.erb</p>

app/views/followers/index.html.erb
<% @follow.reverse.each do |follow| %>
	<div class="boat-list">
	<%= link_to follow.boat.name,  boat_path(follow.boat) %>
	<br> 
	</div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/jobs/create.html.erb
<h1>Jobs#create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/destroy.html.erb
<h1>Jobs#destroy</h1>
<p>Find me in app/views/jobs/destroy.html.erb</p>

app/views/jobs/edit.html.erb
<div class="boat-edit">
	<%= form_for @job do |f| %>
		Name: <%= f.text_field :name %><br>
		Containers <%= f.text_field :containers %><br>
		Cargo: <%= f.text_field :cargo %><br>
		Origin: <%= f.text_field :origin %><br>
		Cost: <%= f.text_field :cost %><br>
		Destination: <%= f.text_field :destination %><br>
		<%= f.submit "Save changes" %>
	<%end%>
</div>

app/views/jobs/index.html.erb
<% @boat.each do |boat| %>
	<div class="boat-list">
	<%= link_to boat.name,  boat_path(boat) %>
	<br> 
	</div>
<% end %>

app/views/jobs/new.html.erb
<h1>Jobs#new</h1>
<p>Find me in app/views/jobs/new.html.erb</p>

app/views/jobs/show.html.erb
<div class="boat-show">
		<h1> Name: <%= @job.name %> </h1> 
		<br>
		<h1>Containers: <%= @job.containers %> </h1> 
		<h1>Cargo: <%= @job.cargo %> </h1> 
		<br>
		<h1>Origin: <%= @job.origin %> </h1> 
		<br>
		<h1>Cost: <%= @job.cost %> </h1> 
		<br>
		<h1>Destination: <%= @job.destination %> </h1> 
		<%= link_to "go back", boats_path%> 
		<br>
		<br>
		<%= link_to "Edit", edit_job_path%> | <%= link_to "Delete the boat", job_path(@job), method: :delete %>
</div>

app/views/jobs/update.html.erb
<h1>Jobs#update</h1>
<p>Find me in app/views/jobs/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShippingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
	<div class="nav-bar">
		<%= link_to "Home",  boats_path %> <%= link_to "Boats list",  jobs_path %> <%= link_to "Following",  followers_path %> <span><%= link_to "Logout",  destroy_user_session_path, method: :delete %></span>
	</div>
<% else %>
	<div class="nav-bar">
	<%= link_to "Sign In",  new_user_session_path %> 
	</div>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/new.html.erb
new_user_session